### ISSUE TITLE
move_group crashing because of moveit_ompl_planners

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_planners#9]
I launch move_group in one window, then launch Rviz with the Motion Planning Plugin already configured in the config file. As soon as Rviz finishes launch move_group crashes. I've backtraced the segfault (below) to the ompl_plugin.cpp call getPlanningAlgorithms(). It crashes when looping through pconfig, which is of type `std::map<std::string, ompl_interface::PlanningConfigurationSettings>`. For some reason the planning context manager is not returning a valid map... it appears `setPlanningConfigurations()` in `planning_context_manager.cpp` is never called.

GDB Backtrace:

```
INFO ros.moveit_ros_planning: Trajectory execution is managing controllers
[New Thread 0x7fffbb4d7700 (LWP 19533)]
[New Thread 0x7fffbacd6700 (LWP 19542)]
[New Thread 0x7fffba4d5700 (LWP 19551)]
 INFO ros.moveit_ros_move_group: MoveGroup running using planning plugin ompl_interface/OMPLPlanner

---Type <return> to continue, or q <return> to quit---
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffde94a700 (LWP 19312)]
0x00007fffd45a198d in ompl_interface::OMPLPlanner::getPlanningAlgorithms(std::vector<std::string, std::allocator<std::string> >&) const () from /home/dave/ros/moveit/devel/lib/libmoveit_ompl_planner_plugin.so
(gdb) bt
#0  0x00007fffd45a198d in ompl_interface::OMPLPlanner::getPlanningAlgorithms(std::vector<std::string, std::allocator<std::string> >&) const () from /home/dave/ros/moveit/devel/lib/libmoveit_ompl_planner_plugin.so
#1  0x00000000004d52fa in move_group::MoveGroupQueryPlannersService::queryInterface(moveit_msgs::QueryPlannerInterfacesRequest_<std::allocator<void> >&, moveit_msgs::QueryPlannerInterfacesResponse_<std::allocator<void> >&) ()
#2  0x00000000004d6eae in ros::ServiceCallbackHelperT<ros::ServiceSpec<moveit_msgs::QueryPlannerInterfacesRequest_<std::allocator<void> >, moveit_msgs::QueryPlannerInterfacesResponse_<std::allocator<void> > > >::call(ros::ServiceCallbackHelperCallParams&) ()
#3  0x00007ffff5cd9c28 in ros::ServiceCallback::call() () from /opt/ros/groovy/lib/libroscpp.so
#4  0x00007ffff5d178e9 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) ()
   from /opt/ros/groovy/lib/libroscpp.so
#5  0x00007ffff5d1938b in ros::CallbackQueue::callAvailable(ros::WallDuration) ()
   from /opt/ros/groovy/lib/libroscpp.so
---Type <return> to continue, or q <return> to quit---
#6  0x00007ffff5d681c6 in ros::AsyncSpinnerImpl::threadFunc() () from /opt/ros/groovy/lib/libroscpp.so
#7  0x00007ffff6812ce9 in thread_proxy () from /usr/lib/libboost_thread.so.1.46.1
#8  0x00007ffff65f0e9a in start_thread (arg=0x7fffde94a700) at pthread_create.c:308
#9  0x00007ffff3e8dcbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#10 0x0000000000000000 in ?? ()
```

**Comment by isucan** [comment]
I've been making a _lot_ of changes these days. Can you check if this is still an issue with the most recent version? I can't seem to replicate this.

**Comment by davetcoleman** [comment]
It appears to be a race condition:
Ioan: "so it sounds like the capability gets called before the context is initialized. the plugin gets constructed and a request is made before the context is sat"

**Comment by isucan** [comment]
you still have this problem? I still cannot replicate it.

**Comment by isucan** [comment]
ping?

**Comment by davetcoleman** [comment]
i haven't seen this lately so we'll assume this problem is gone for now
